services:
  app:
    image: davileitee/auladevops-app:staging
    container_name: marmitatech-app-v2
    ports:
      - "8093:4000"
    environment:
      DB_HOST: mysql-infra
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: marmitadbDavi
    networks:
      - rede_alunos

networks:
  rede_alunos:
    external: true
